# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95fa15c87caf10ae48865c87c8522a8b152b146833deb01df5aba2e114372f5f069f8e15d1200f629597f8a2ba675d46709fdc753ba4b1e97e930dc592396f0e

test:
  secret_key_base: 65cc46469368cceda45656305324f4055180a135f70cbd3ce91fbacbeba3ea0328dd87d014063e852fddc6e839e521987a28e06760893e0c82c7c47b4f44424e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
